# Generated by Django 4.1.6 on 2023-03-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListBookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='listbook',
            name='category',
        ),
        migrations.AddField(
            model_name='listbook',
            name='category',
            field=models.ManyToManyField(to='biblioteka_app.listbookcategory'),
        ),
    ]
