# Generated by Django 4.1.6 on 2023-03-03 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka_app', '0002_listbookcategory_remove_listbook_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listpeople',
            old_name='team_scout',
            new_name='note',
        ),
    ]
