# Generated by Django 4.1.6 on 2023-04-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka_app', '0006_alter_listphoto_description_alter_listphoto_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listphoto',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
