# Generated by Django 4.1.6 on 2023-05-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteka_app', '0010_alter_openinghours_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openinghours',
            name='day',
            field=models.CharField(choices=[('Poniedziałek', 'Mon'), ('Wtorek', 'Tue'), ('Środa', 'Wed'), ('Czwartek', 'Thu'), ('Piątek', 'Fri'), ('Sobota', 'Sat'), ('Niedziela', 'Sun')], max_length=15, unique=True),
        ),
    ]
